### ISSUE TITLE
changin source and target level?

### ISSUE THREAD

**Issue by scgm11** [asterisk-java/asterisk-java#139]
what do you think in changing

sourceCompatibility = 1.6
targetCompatibility = 1.6

to 1.8??

**Comment by bsutton** [comment]
Would love to, but I think we are getting ahead of ourselves.

We are still using 1.7 and I imagine a lot of other users are in a 
similar situation.


What are the thoughts of other community members?

Brett

**Comment by michaelrice** [comment]
Im still on 1.7, and on other projects I work on that are fairly popular in the enterprise space ([yavijava](https://github.com/yavijava/yavijava) for example) it is still trying to stay 1.6 because Ive had people file [bugs](https://github.com/yavijava/yavijava/issues/151) about the 1.6 support not being correct which leads me to believe that as terrible as it is a lot of enterprise folks may still be stuck using 1.6 I think at this time 1.8 is a bit too aggressive but Im on board for 1.7

**Comment by srt** [comment]
I would like to refer to http://www.oracle.com/technetwork/java/eol-135779.html
Java 1.7 is End of Public Updates since Apr 2015 which is more than a year ago. So I am +1 for source and target compatibility set to 1.8 for the current development version and next major release.

**Comment by bsutton** [comment]
I think we would break a lot of projects if we went to 1.8. We still haven't moved, although it is going to happen in the near future.
I'm inclined to move to 1.7 and look at 1.8 in a year or so.

**Comment by bsutton** [comment]
For the 2.0 release we are going to move to java 1.7, 1.x will remain on the 1.6 source

**Comment by scgm11** [comment]
do you commit the sourcetarget to 1.7 then?

**Comment by sabahirfan** [comment]
We are using 1.8
