### ISSUE TITLE
The application delimiter is now the comma, not the pipe. Did you forget to convert your dialplan?

### ISSUE THREAD

**Issue by albfan** [asterisk-java/asterisk-java#147]
After passing some variables to a OriginateAction Asterisk start to complaint.

forums says that it is an old change (from somewhere between 1.4 and 1.6)

http://forums.asterisk.org/viewtopic.php?f=1&t=88100

so don't know where to look. 

Variables are passed with pipes anyway? This test seems to show it does.

https://github.com/asterisk-java/asterisk-java/blob/master/src/test/java/org/asteriskjava/manager/internal/ActionBuilderImplTest.java#L142

Could be a message composed with variables which fools asterisk adding undesired pipes?

**Comment by albfan** [comment]
Seems a problem with config, sorry for the noise

**Comment by bsutton** [comment]
So the issue is that we really need to be detecting the version of 
asterisk on startup and then setting the delimiter according to the 
version of asterisk.

There are a couple of issues around this.

1) what if a single application connects to multiple asterisk servers 
running different versions.

2) I have a vauge feeling there is a startup sequencing issue (but it 
doesn't quite make sense now) that we need to know the version before 
asterisk tells us what version is running.

The other option would be to have the api require the code to tell us 
what version of asterisk is being run, but I don't like this idea.

**Comment by albfan** [comment]
Guess you will find interesting this lines then:

https://github.com/AsterNET/AsterNET/blob/91d0c8d10bed3fd969c31ef4160931fba0111f6c/Asterisk.2013/Asterisk.NET/Manager/ManagerConnection.cs#L1513

**Comment by bsutton** [comment]
Didn't know that existed!! Good find.

So looks like we just need to change the code to use VAR_DELIMITER. That 
does assume that different command are consistent in the usage of 
delimiters which might not be a good assumption in asterisk.

I've passed this on to our dev team, but if anyone can contribute 
patches that use VAR_DELIMITER they would be very welcome.

Brett
