### ISSUE TITLE
Wrong behaviour @ DialCommand.java

### ISSUE THREAD

**Issue by wbarroz** [asterisk-java/asterisk-java#179]
Hi folks!
I was struggling to make the function Dial works, and eventually made it with this "fix" in DialCommand.java, around line 32; was:
String command = "EXEC " + escapeAndQuote("dial") + " " + escapeAndQuote(target) + "|"
become:
String command = "EXEC " + escapeAndQuote("dial") + " " + escapeAndQuote(target) + ","

The error was:
    -- Executing [6012@internal_users:1] AGI("SIP/phone-1-00000001", "agi://172.22.26.201/callin.agi") in new stack
    -- AGI Script Executing Application: (dial) Options: (SIP/phone-2|33)
  == Using SIP RTP CoS mark 5
[Nov 18 17:44:14] ERROR[24910][C-00000002]: netsock2.c:305 ast_sockaddr_resolve: getaddrinfo("phone-2|33", "(null)", ...): Temporary failure in name resolution
[Nov 18 17:44:14] WARNING[24910][C-00000002]: chan_sip.c:6312 create_addr: No such host: phone-2|33

That use to happen when I called, in an AgiScript:
dial("SIP/phone-2",33,null);

After the "fix":
    -- Executing [6012@internal_users:1] AGI("SIP/phone-1-00000009", "agi://172.22.26.201/callin.agi") in new stack
    -- AGI Script Executing Application: (dial) Options: (SIP/phone-2,33)
  == Using SIP RTP CoS mark 5
    -- Called SIP/phone-2
    -- SIP/phone-2-0000000a is ringing

Even if was a wrong fix, can you give-me a feedback?

Thank you very much!

**Comment by bsutton** [comment]
what version of asterisk are you using?
There was a change in delimiters used (can't remember what version).
Also which version of asterisk java are you using? I have a vauge memory that a fix for this has already been posted.

**Comment by wbarroz** [comment]
Hi! Thank you for the answer!
The Asterisk is 14 and Asterisk-Java 2.0.
BTW, where could I get more details on using the AMI or Activities? I
couldn't start on these.
Back to the original problem, I couldn't figure out other way to send the
correct command.

Once more, thank you very much!

Em 21 de nov de 2016 19:34, "Brett Sutton" <notifications@github.com>
escreveu:

**Comment by bsutton** [comment]
so the delimiter changed after 1.4 and the 2.x build doesn't yet have the required logic to handle the difference.
I've asked the development team to look at a method to pass the asterisk version to the agi factory so that it can manage these type of differences.
For the moment it sounds like your patch is adequate for the job.
As to documentation on activities. We are trying to get some resources applied to updating the documentation.
At this point you can find the start of an overview here:
https://github.com/asterisk-java/asterisk-java/wiki/Activities

And there are some sample code here:
https://github.com/asterisk-java/asterisk-java/tree/master/src/main/java/org/asteriskjava/examples/activities

As to the AMI details there isn't a lot except what you have already seen on this site.
Happy to accept documentation pull requests :)

**Comment by bsutton** [comment]
https://github.com/asterisk-java/asterisk-java/wiki/Getting-Started
