### ISSUE TITLE
OnNoAnswer even if the call is answered

### ISSUE THREAD

**Issue by drenda** [asterisk-java/asterisk-java#207]
Hi, I use this library from many years. At the moment I'm using the beta release from several months. I never found something bad, but in past days I'm experiencing troubles.

I use `OriginateAction` (async) to create outbound calls and I use `OriginateCallback` to get events on the channel after I sent the call.

In the past days I noticed several calls for which I receive the `onNoAnswer()` from Asterisk Java but unfortunately those calls are answered. In fact I see also all `PropertyChange` on the channel because I added a listener. I see the call is answered, audio is played ect ect...and at the end I receive the Hangup(16).

I'm wondering if you are experiencing the same problem. Thanks

**Comment by bsutton** [comment]
no haven't seen it here and we use similar methods.

Have you updated your version of asterisk?

**Comment by bsutton** [comment]
closed as no further details provided.

**Comment by Erbos** [comment]
Hello:
I was recently using the library, and I had the same problem, the callbacks apparently are not working well in the case of the OriginateAsync method in the case of Local Channels. I am currently working with Astersik 13.14.1 and astersik-java 2.0.2. I made a fork of the master and fix it, adding the relevant validations for the 2 remaining channels (in the special Local case), since the UP state, was only looking for the channel that came in the event and this does not always happen, that is, sometimes the UP state (the call was answered) comes in one of the other two linked channels.

**Comment by bsutton** [comment]
Local channels are always problematic we try to avoid using whenever
possible.

**Comment by Erbos** [comment]
I totally agree, but I think there are specific cases in which it is advisable to use.

**Comment by bsutton** [comment]
Advisable ? Unavoidable yes :)

I would be interested to know what the use case is in the example.

Having said that Asterisk-Java should work for all cases, so any patch
would be welcomed.
