### ISSUE TITLE
Missing AsteriskQueueMember.Location in asterisk 13.19.0

### ISSUE THREAD

**Issue by sondangphi** [asterisk-java/asterisk-java#246]
Hi guys.

Recently I download Asterisk-Java 2.0.2 release and tested it, that is a great thing in my life. I tested with asterisk 11.0, it works well. But it shows an issue when I make test with asterisk 13.19.0. That is I can't get AsteriskQueueMember.Location (it's emty in asterisk 13, but it shows SIP/XXXX, LOCAL/XXXX...in asterisk 11). I hope you will find out the problem and update back to me. I'll make the test again.

Thank for your sharing.

**Comment by sondangphi** [comment]
I got some info:
-------------------------------
WARNING: Unsupported protocol version 'Asterisk Call Manager/2.10.3'. Use at your own risk

WARNING: Unable to set property 'pausedreason' to '' on org.asteriskjava.manager.event.QueueMemberAddedEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
May 07, 2018 4:44:36 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'incall' to '0' on org.asteriskjava.manager.event.QueueMemberAddedEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
May 07, 2018 4:44:36 PM org.asteriskjava.manager.internal.AbstractBuilder setAttributes
WARNING: Unable to set property 'incall' to '0' on org.asteriskjava.manager.event.QueueMemberAddedEvent: no setter. Please report at https://github.com/asterisk-java/asterisk-java/issues
May 07, 2018 4:44:36 PM org.asteriskjava.live.internal.AsteriskQueueImpl addMember
INFO: Adding new member to the queue KENH_HELP: AsteriskQueueMember[location='null'state='DEVICE_NOT_INUSE'paused='false'membership='dynamic'queue='KENH_HELP'callsTaken='0'lastCall='0'systemHashcode=1211441282]

May 07, 2018 4:42:26 PM org.asteriskjava.live.internal.AsteriskQueueImpl getMemberByLocation
SEVERE: Requested member at location null not found!
May 07, 2018 4:42:26 PM org.asteriskjava.live.internal.QueueManager handleQueueMemberPausedEvent
SEVERE: Ignored QueueMemberPausedEvent for unknown member null
----------------------------
Hardly to know how does API work. I made test, sometime it got the location, sometime it returns null value, in my opinion may be some member events will set location to null, but I can't find it out. Sorry.

**Comment by titaniche** [comment]
I have the same problem. Asterisk version: 13.22.0,
I have a handler that handles the QueueMemberEvent, and the event return location = null. And there are exceptions:
```
- {AsteriskQueueImpl}: Requested member at location null not found!
- {QueueManager}: Ignored QueueMemberStatusEvent for unknown member null
- {QueueManager}: Ignored QueueMemberRemovedEvent for unknown agent name: <correct_name> location: null queue: <correct_queue>
```
Especially, the context and extension is null too, but StateInterface is correct (example: hint:1111@ext-local)
May be there is a way to solve this issue? Thanks.

**Comment by bsutton** [comment]
You are going to have to look at the raw event that asterisk is pushing 
up and see how it is being converted.

**Comment by titaniche** [comment]
I mean i do not understand, what "Location" is field? And why do many QueueMemberEvent and same classes check this field, but the setter for this field is not called?
I have an application with own ManagerEventListener implementation. The listener handle some event in QmemeMemberEvent scope (for example adding, removeng, change state in queue, set paused and so on).
When the application started - there is the first call `AsteriskServer.getQueues()` method and its returned correct data (especially queue members with correct Location fields).
Then the Asterisk generating some QueueMemberEvent (for example, member removed from queue). And in event  the value of Location is null. Also, if i check the call structure - the head event does not have location field value, just null (method: `ManagerConnectionImpl.fireEvent(event)`).
P.S. The field Interface has a target value of Location (if i understand right). But cheking of member in queue in method `AsteriskQueueMemberImpl getMemberByLocation(String location)` is referenced on the field Location, but the Location field does not settied before.

**Comment by titaniche** [comment]
I just try to add a `setLocation(interface)` in `setInterface(interface)` methods for some QueueMember<type>Event classes (<Added>, <Pause>, <Removed>, <Status>).
Example:
```
public void setInterface(String _interface)
{
	this._interface = _interface;
	// Manual changed
	setLocation(_interface);
}
```
Not sure that this the right way, but don't have exceptions yet.

**Comment by bsutton** [comment]
Given that you have just created an infinite recursion, that is certainly NOT the correct way ;)

**Comment by titaniche** [comment]
I will try to describe the whole sequence of actions that I perform.
Task: Process queue events, such as adding, deleting, pausing.
Which steps did I take?
1) Using this library, I connect to Asterisk. Example:
```
asteriskServer = new DefaultAsteriskServer(hostname, port, username, password);
asteriskServer.initialize();
```
2) I install my own implementation of ManagerEventListener.
```
asteriskServer.getManagerConnection().addEventListener(eventListener);
```
In the implementation of ManagerEventListener I'll show an example of handling the event of adding a member to the queue:
```
@Override
public void onManagerEvent(ManagerEvent managerEvent)
{
	if (managerEvent instanceof QueueMemberAddedEvent)
		handleEvent((QueueMemberAddedEvent) managerEvent);
}

private void handleEvent(QueueMemberAddedEvent event)
{
	// Just for example show some fields
	System.out.println("---QueueMemberAddedEvent---");
	System.out.println("Exten: " + event.getExten());
	System.out.println("Member name: " + event.getMemberName());
	System.out.println("Location: " + event.getLocation());
	System.out.println("Interface: " + event.getInterface());
	System.out.println("Queue: " + event.getQueue());
	System.out.println("Status: " + QueueMemberState.valueOf(event.getStatus()));
	System.out.println("StateInterface: " + event.getStateinterface());
	if (event.getTimestamp() != null)
		System.out.println("Timestamp: " + new Date(event.getTimestamp().longValue()));
	System.out.println("Interface: " + event.getInterface());
	System.out.println("Membership: " + event.getMembership());
}
```
As a result, I have Exten = null, Location = null. And due to the fact that Location = null, I have some exceptions (https://github.com/asterisk-java/asterisk-java/issues/246#issuecomment-413827078), but not always (sometimes they go out, sometimes. For example, now I check - exceptions do not work).

Output result:
```
--- QueueMemberAddedEvent ---
Exten: null
Member name: a
Location: null
Interface: Local / 1111 @ from-queue / n
Queue: 10001
Status: DEVICE_INUSE
StateInterface: hint: 1111 @ ext-local
Interface: Local / 1111 @ from-queue / n
Membership: dynamic
```
At the moment I've added the setter in the example above, but as you suggested, this is a completely wrong way. At the moment it's working for me, but I'd like to do it right (I've been doing Asterisk relatively recently, and Java in general).

P.S. Forgive me for my grammar and generally for the language :(

**Comment by pk1057** [comment]
Since asterisk12 they renamed some queue event fields without proper documentation.
Only the QueueMember event   has the field location.
For all other Queue events the field was renamed to interface !

I will working on a patch for this problem

**Comment by pk1057** [comment]
Please look at my PR #289 with fixes for Queue Event Field Handling

**Comment by titaniche** [comment]
Well thank you. But, at the moment I want to use the level of abstraction `live`. However, when working with queue members and there are some problems. For example, for `AsteriskQueueMember`, the `location` field is still used, and this is an important field by which at this level of abstraction it is possible to determine which particular queue member you have to work with. For example, I used my `AsteriskQueueListener` implementation. At the event of adding a member (`onMemberAdded()`) I get information about the added queue member, but there is an empty value for `location`. Here is an example of my logger:
`2019-04-18 12:48:54.752 [INFO] : com.prime.asterisk.core.manager.event.listener.live.AMIAsteriskQueueListener.onMemberAdded()[line:85] - Added queue member AsteriskQueueMember[location='null'state='DEVICE_INUSE'paused='false'membership='dynamic'queue='10007'callsTaken='0'lastCall='0'systemHashcode=463097527]`
Given your previous posts, in the `AsteriskQueueMember` implementation, you should also change the `location` to `_interface`.
P.S. At the moment, the `ManagerEvent` event handling mechanism is used, but the implementation with the help of `live` objects actually looks more attractive, but due to these problems I cannot completely restructure myself for this mechanism. By the way, if you handle `ManagerEvent` events, then you can get there in addition to everything `memberName`, but I did not see this field in the `live` object.

**Comment by titaniche** [comment]
Made minor edits (just added an `iface` field to some objects related to `AsteriskQueueMember`). In general, when the event associated with the queue member is generated, the added field (`iface`) has a value (while location = null). True, there was another subtlety:
`AsteriskQueueListener` as well as `PropertyChangeListener` for `AsteriskQueueMember` for some reason does not generate events for already existing objects. That is, when I connect to Asterisk, and then I get a list of queues (along with their members), I add the `AsteriskQueueListener` implementation to `AsteriskQueue`, and `PropertyChangeListener` for the corresponding members, then no event generation takes place. Events are generated only when creating a new queue member. If, for example, an existing queue member goes into pause, then `QueueMemberStatusEvent` events will not be generated. However, if it enters the queue, subsequent events (including a `QueueMemberStatusEvent`) are generated. I do not understand why.

**Comment by pk1057** [comment]
You are right,
i will add this next week to the patch.

peter

**Comment by titaniche** [comment]
For information, I will give you some of your solutions.
Used sources of your library 2.0.4
Made some changes:
1) Added an `iface` field for most events associated with a queue member
2) In places where the `location` field is used (roughly speaking, `getLocation()` is called) changed to added `iface` (replaced call to `getInterface()`)
3) In addition, I had to make the logic of work so that when starting my application using your library, I had to get an up-to-date list of queues and queue members. However, due to the fact that in paragraph 2 I changed the code to the `getInterface()` method call, the asterisk did not return me the list of queue members. I tried to understand what it is connected with and came to the conclusion that the problem is connected with the use of both: `location` (as first) and `interface` (as second and next). The fact is that during the initialization of the implementation `ManagerConnection` asterisk fills the `location` field ... and later on it generates events using the `interface` (`iface`) field. So I had to change the `addMember(...)` method in `AsteriskQueueMemberImpl` a bit:
```
	void addMember(AsteriskQueueMemberImpl member)
	{
		synchronized (members)
		{
			// Check if member already exists
			if (members.containsValue(member))
			{
				return;
			}
			// If not, add the new member.
			logger.info("Adding new member to the queue " + getName() + ": " + member.toString());
//            members.put(member.getLocation(), member);
			if (member.getInterface() != null)
			{
				members.put(member.getInterface(), member);
			}
			else if (member.getLocation() != null)
			{
				members.put(member.getLocation(), member);
			}
			else
			{
				logger.warn("Cannot add member with incorrect interface/location: " + member);
			}
		}

		fireMemberAdded(member);
	}
```
Thus, in priority, we use `getInterface()`, but if it is empty, we try to get it with `getLocation()`.
Of course, these decisions are essentially temporary.
I attach the archive with the source code, where I made some edits, please see (unfortunately I can not provide just a link to the project, because there is no public access to it). Maybe it will help somehow.
P.S. Sorry for my language)
[asterisk-java-master.zip](https://github.com/asterisk-java/asterisk-java/files/3156224/asterisk-java-master.zip)

**Comment by pk1057** [comment]
So, digged a little further through asterisk change information.
In asterisk 12 : "The majority of Queue events have had the Location field renamed to the Interface field. 
". Well this fits to my findings, nearly all Queue Events have this field, despite of one.
So i will change my patch to match for asterisk 12 and will incorporate it to asterisk-java-3.
Will this be ok ?

**Comment by titaniche** [comment]
Yes of course. I hope it will be so good if I understand you correctly. Thank)
