### ISSUE TITLE
No longer pushing to maven central?

### ISSUE THREAD

**Issue by seanbright** [asterisk-java/asterisk-java#292]
In README.md, versions 2.0.3 and 2.0.4 are using third-party maven repos instead of maven central. Are you no longer pushing releases to maven central?

**Comment by Polve** [comment]
I was asking the same question: what's the problem?
Why did you close the project, do you have an answer?

**Comment by seanbright** [comment]
I didn’t get a response to my question for 4 months and closed it out of frustration. I just implemented my own AMI library for internal use and gave up on this project.

**Comment by bsutton** [comment]
Sorry folks, I can understand the frustration on this one.

The reality is currently we are serverly resource constrained due to a large project and this is unlikely to change in until the end of the year.

We are however keen to see a more continuous release schedule.

One of the blocking issue is release keys for maven.
Whilst we take a fairly liberal approach to adding contributors we are less keen to share the release keys.

The  issue is visibility. With a contributor it's easy to monitor contributions and wind them back if necessary with a maven release it's a little uglier.

As such we are looking for a simpler release mechanism that can be done via GitHub which will allow contributors to assist with releases.

As some of you know we have been experimenting with a maven plugin which can pull directly from GitHub tags. This seems to work but doesn't have the same visibility as maven Central and requires more work in the pom.

I've been keeping an eye on GitHub new registry feature.

https://help.github.com/en/articles/configuring-apache-maven-for-use-with-github-package-registry.

I rather like this technique as it means contributors can push a release and we have visibility.

But to move forward on this we need some help.

Would anyone be prorated to volunteer some time to investigate this feature?

We are happy to add you as a contributor providing you can show a history of productive contributions to any active Java based open source project.

**Comment by bsutton** [comment]
In the comments regarding 11 in still of the opinion that it's still to early 

There are large no's of project which still aren't ready for 9.

I would like to get some resource to make it package work with 9. I've gone blank right now but there is a manifest or similar that you can assess to an 8 project which removes a number of earrings when use in a 9 project.

The other option is we could create two release streams, an 8 stream and an 11 stream.

But again we need contributors to help.

**Comment by Polve** [comment]
I can't understand the problem related to maven: the deployment process is automated and if you don't want to share the keys you can just run the command to publish from a github tag.

BTW I use gradle and I'm unable to understand how to use the github repository so I'm still using version 1.0 of the software.

Java11 is the current LTS, it's already one year old, and it's the only java release available on all modern linux distributions (debian, ubuntu, etc) and so in my opinion it should be the baseline for a new version.

If there are projects stuck to old versions (that's strange since there are usually no big problems of compatibility) they can use an older asterisk-java release.

**Comment by bsutton** [comment]
Alessandro,
our experience with maven central is that its actually quite painful to
push to maven central.
There are lots of rules you have to get right (osgi export, jar signing
.....).
If everything goes right it takes us about an hour, if it doesn't its a
mess to sort out (errors are cryptic the maven central UI is a pain to work
with).

Hence the suggestion of looking at the github registry option.

As to java 11 I think you are misunderstanding what the issues are.

A java library should always be behind the curve when it comes to java
version requirements as it opens it up to the library to the broadest no.
of users.
There is no inherent gain, at this point, in moving to java 11 as we aren't
about to refactor the code base to use any java 11 features.
The fact that modern OS' are shipping with java 11 is also not relevant as
we are talking about compile time requirements not run time requirements.
There are also significant no.s of libraries that don't work with java 9+
and I would expect we are still 2-3 years away from this no longer being an
issue.
I would also expect that there is some work to be done to create a java 9
compatible version (manifest etc). Again we would need a contributor to
help with this. As I've previously stated I wouldn't object to creating two
release branches an v8 and a v11 if we had someone that could do the work.

The gradle problem is certainly an issue which the suggest github registry
option would fix.

Brett

**Comment by Polve** [comment]
Thanks for the explaination bsutton, highly appreciated.
I understand the policy about java11 but I suppose you can enable java11 syntax and generate java8 bytecode.

Anyway I can't see the problem with maven publishing: I myself publish a package I don't have time to work on it and other people does. When a new release is needed, after pulling the latest version, it's just a matter of doing something similar to

> mvn versions:set -DnewVersion=X.Y.Z

or simply:

> mvn clean deploy -P release

(of course I'm using maven Nexus plugin)
Is this different for you?
